=== GSA/ITDB-schema/draftBY19/CIORating/Schemas/Exchange/serviceResponse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.itdashboard.gov/serviceResponse"
        xmlns:sr="http://www.itdashboard.gov/serviceResponse"
        xmlns:tns="http://www.itdashboard.gov/service"
        xmlns:cioRating-type="urn:us:gov:cioRating-type"
        elementFormDefault="qualified"
        version="FY_2019">

  <annotation>
    <documentation>
      1. This schema SHOULD NOT BE used to Submit Data to ITDashboard.
      2. Any dates that are referred in this schema will be in 'YYYY-MM-DD' format.
    </documentation>
  </annotation>

  <import namespace="http://www.itdashboard.gov/service" schemaLocation="serviceRequest.xsd"/>
  <import namespace="urn:us:gov:cioRating-type" schemaLocation="../Subset/cioRatingTypes.xsd"/>

  <element name="operationResults" type="sr:operationResultsType"/>

  <complexType name="operationResultsType">
    <choice>
      <element name="schemaValidationError" type="sr:messagesType"/>
      <element name="investment" type="sr:investmentResultType" maxOccurs="unbounded"/>
      <element name="messages" type="sr:messagesType"/>
    </choice>
    <attribute name="validateOnlyIndicator" type="boolean"/>
    <attribute name="submissionId" type="string"/>
  </complexType>

	<!-- 
	    Should the minOccurs be removed?
	 -->

  <complexType name="simpleResultType">
    <sequence>
      <element name="getCIORatingResult" type="sr:getCIORatingResultType" maxOccurs="unbounded" minOccurs="0"/>
      <element name="setCIORatingResult" type="sr:CIORatingResultType" maxOccurs="unbounded" minOccurs="0"/>
      <element name="message" type="sr:messageType" maxOccurs="unbounded" minOccurs="0"/>
    </sequence>
  </complexType>

  <complexType name="getCIORatingResultType">
    <sequence>
      <element name="CIORating" type="sr:CIORatingType" maxOccurs="unbounded" minOccurs="0"/>
      <element name="request" type="tns:operationsOut" maxOccurs="unbounded" minOccurs="0"/>
      <element name="message" type="sr:messageType" maxOccurs="unbounded" minOccurs="0"/>
    </sequence>
    <attribute name="id" type="string" use="required"/>
  </complexType>

  <complexType name="CIORatingResultType">
    <sequence>
      <element name="CIORating" type="sr:CIORatingType" maxOccurs="unbounded" minOccurs="0"/>
      <element name="request" type="tns:operationsOut" maxOccurs="unbounded" minOccurs="0"/>
      <element name="message" type="sr:messageType" maxOccurs="unbounded" minOccurs="0"/>
    </sequence>
    <attribute name="id" type="string" use="required"/>
  </complexType>

  <complexType name="messageType">
    <simpleContent>
      <extension base="string">
        <attribute name="xpath" type="string"/>
        <attribute name="level">
          <simpleType>
            <restriction base="string">
              <enumeration value="error"/>
              <enumeration value="warning"/>
              <enumeration value="info"/>
            </restriction>
          </simpleType>
        </attribute>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="CIORatingType">
    <sequence>
      <element name="cioRatingEval" type="cioRating-type:cioRatingType"/>
      <element name="cioComment" type="cioRating-type:longTextString"/>
    </sequence>
  </complexType>

  <complexType name="investmentResultType">
    <sequence>
      <choice>
        <element name="success" type="sr:simpleResultType"/>
        <element name="failure" type="sr:simpleResultType"/>
      </choice>
    </sequence>
    <attribute name="uniqueInvestmentIdentifier" type="cioRating-type:investmentIdentifierType" use="required">
    </attribute>
  </complexType>

  <complexType name="messagesType">
    <sequence>
      <element name="message" type="sr:messageType" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

</schema>

=== GSA/ITDB-schema/src/CIORating/Examples/Response_success.xml
<?xml version="1.0" encoding="UTF-8"?>
<sr:operationResults xmlns="http://www.itdashboard.gov/service"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xmlns:sr="http://www.itdashboard.gov/serviceResponse"
                     xsi:schemaLocation="http://www.itdashboard.gov/serviceResponse ../Exchange/serviceResponse.xsd">
  <sr:investment uniqueInvestmentIdentifier="000-000000000">
    <sr:success>
      <sr:getCIORatingResult id="String">
        <sr:CIORating>
          <sr:cioRatingEval>1</sr:cioRatingEval>
          <sr:cioComment>a</sr:cioComment>
        </sr:CIORating>
      </sr:getCIORatingResult>
      <sr:setCIORatingResult id="String">
        <sr:CIORating>
          <sr:cioRatingEval>1</sr:cioRatingEval>
          <sr:cioComment>a</sr:cioComment>
        </sr:CIORating>
      </sr:setCIORatingResult>
      <sr:message>String</sr:message>
    </sr:success>
  </sr:investment>
</sr:operationResults>

<!-- test -->
